
import type { User } from 'firebase/auth';
import type { Movie } from '@/types/movie';

export const MOCK_VIDEO_URL = "https://archive.org/download/BigBuckBunny_124/Content/big_buck_bunny_720p_surround.mp4";

export const MOCK_USER_CREDENTIALS = {
  email: 'admin@admin.com',
  password: 'admin',
};

// A more complete mock User object
export const mockUser: User = {
  uid: 'mock-admin-uid',
  email: MOCK_USER_CREDENTIALS.email,
  displayName: 'Admin User',
  photoURL: `https://picsum.photos/seed/admin-${MOCK_USER_CREDENTIALS.email}/40/40`,
  emailVerified: true,
  isAnonymous: false,
  metadata: {
    creationTime: new Date().toISOString(),
    lastSignInTime: new Date().toISOString(),
  },
  providerData: [{
    providerId: 'password',
    uid: 'mock-admin-uid',
    displayName: 'Admin User',
    email: MOCK_USER_CREDENTIALS.email,
    phoneNumber: null,
    photoURL: `https://picsum.photos/seed/admin-${MOCK_USER_CREDENTIALS.email}/40/40`,
  }],
  refreshToken: 'mock-refresh-token',
  tenantId: null,
  delete: async () => { console.warn('Mock user delete called'); },
  getIdToken: async (_forceRefresh?: boolean) => 'mock-id-token',
  getIdTokenResult: async () => ({
    token: 'mock-id-token',
    expirationTime: new Date(Date.now() + 3600 * 1000).toISOString(),
    authTime: new Date().toISOString(),
    issuedAtTime: new Date().toISOString(),
    signInProvider: 'password',
    signInSecondFactor: null,
    claims: { admin: true }, // Example claim
  }),
  reload: async () => { console.warn('Mock user reload called'); },
  toJSON: () => ({
    uid: 'mock-admin-uid',
    email: MOCK_USER_CREDENTIALS.email,
    displayName: 'Admin User',
    photoURL: `https://picsum.photos/seed/admin-${MOCK_USER_CREDENTIALS.email}/40/40`,
    emailVerified: true,
    isAnonymous: false,
  }),
};


export const mockMovies: Movie[] = [
  {
    id: 'mock-movie-1',
    title: 'The Great Mock Adventure',
    description: 'An epic journey through a world of mocks and stubs. Will our heroes find the real data?',
    posterUrl: 'https://picsum.photos/seed/mockmovie1/300/450',
    videoUrl: MOCK_VIDEO_URL,
    genre: 'Adventure',
    duration: '1h 45m',
    rating: 4.2,
    year: 2023,
  },
  {
    id: 'mock-movie-2',
    title: 'Cybernetic Dreams (Mock Edit)',
    description: 'In a future where data is king, one AI decides to mock the system.',
    posterUrl: 'https://picsum.photos/seed/mockmovie2/300/450',
    videoUrl: MOCK_VIDEO_URL,
    genre: 'Sci-Fi',
    duration: '2h 10m',
    rating: 4.8,
    year: 2024,
  },
  {
    id: 'mock-movie-3',
    title: 'Comedy of Fallbacks',
    description: 'When the API goes down, the backup plan is... surprisingly hilarious.',
    posterUrl: 'https://picsum.photos/seed/mockmovie3/300/450',
    videoUrl: MOCK_VIDEO_URL,
    genre: 'Comedy',
    duration: '1h 33m',
    rating: 3.9,
    year: 2022,
  },
  // Add more mock movies as needed to test pagination
  {
    id: 'mock-movie-4',
    title: 'Placeholder Romance',
    description: 'Two data points find love in a test environment.',
    posterUrl: 'https://picsum.photos/seed/mockmovie4/300/450',
    videoUrl: MOCK_VIDEO_URL,
    genre: 'Romance',
    duration: '1h 52m',
    rating: 4.1,
    year: 2023,
  },
  {
    id: 'mock-movie-5',
    title: 'The Lorem Ipsum Enigma',
    description: 'A detective tries to solve a mystery written entirely in placeholder text.',
    posterUrl: 'https://picsum.photos/seed/mockmovie5/300/450',
    videoUrl: MOCK_VIDEO_URL,
    genre: 'Mystery',
    duration: '1h 59m',
    rating: 4.4,
    year: 2024,
  },
  {
    id: 'mock-movie-6',
    title: 'Seeder Kings: The Uprising',
    description: 'Mock data takes over the kingdom.',
    posterUrl: 'https://picsum.photos/seed/mockmovie6/300/450',
    videoUrl: MOCK_VIDEO_URL,
    genre: 'Fantasy',
    duration: '2h 05m',
    rating: 3.7,
    year: 2022,
  },
   {
    id: 'mock-movie-7',
    title: 'Action Packed Placeholders',
    description: 'Explosions and car chases, all using default assets!',
    posterUrl: 'https://picsum.photos/seed/mockmovie7/300/450',
    videoUrl: MOCK_VIDEO_URL,
    genre: 'Action',
    duration: '1h 30m',
    rating: 4.0,
    year: 2023,
  },
  {
    id: 'mock-movie-8',
    title: 'The Debugging Detective',
    description: 'She solves crimes by reading console logs.',
    posterUrl: 'https://picsum.photos/seed/mockmovie8/300/450',
    videoUrl: MOCK_VIDEO_URL,
    genre: 'Crime',
    duration: '1h 48m',
    rating: 4.3,
    year: 2024,
  },
  {
    id: 'mock-movie-9',
    title: 'Horror of the Null Pointer',
    description: 'It comes for your variables in the night.',
    posterUrl: 'https://picsum.photos/seed/mockmovie9/300/450',
    videoUrl: MOCK_VIDEO_URL,
    genre: 'Horror',
    duration: '1h 25m',
    rating: 3.5,
    year: 2022,
  },
  {
    id: 'mock-movie-10',
    title: 'Animated Stubs',
    description: 'A heartwarming tale of placeholder characters coming to life.',
    posterUrl: 'https://picsum.photos/seed/mockmovie10/300/450',
    videoUrl: MOCK_VIDEO_URL,
    genre: 'Animation',
    duration: '1h 35m',
    rating: 4.6,
    year: 2023,
  },
  {
    id: 'mock-movie-11',
    title: 'Documentary: The Life of a Mock Object',
    description: 'An in-depth look at the unsung heroes of software testing.',
    posterUrl: 'https://picsum.photos/seed/mockmovie11/300/450',
    videoUrl: MOCK_VIDEO_URL,
    genre: 'Documentary',
    duration: '1h 15m',
    rating: 4.9,
    year: 2024,
  },
  {
    id: 'mock-movie-12',
    title: 'Western Standoff at Firebase Gulch',
    description: 'When the API key is missing, tensions rise.',
    posterUrl: 'https://picsum.photos/seed/mockmovie12/300/450',
    videoUrl: MOCK_VIDEO_URL,
    genre: 'Western',
    duration: '1h 40m',
    rating: 3.8,
    year: 2022,
  },
   {
    id: 'mock-movie-13',
    title: 'The Infinite Scroll Saga',
    description: 'They thought they reached the end, but there was always more... mock data.',
    posterUrl: 'https://picsum.photos/seed/mockmovie13/300/450',
    videoUrl: MOCK_VIDEO_URL,
    genre: 'Drama',
    duration: '2h 30m',
    rating: 4.1,
    year: 2023,
  }
];
