
name: Build and Generate Reports

on:
  push:
    branches:
      - dev # Deploys on push to master branch

jobs:
  build_and_reports:
    environment: Development
    runs-on: ubuntu-latest
    permissions:
      contents: read # Allow checkout
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Using Node.js 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check Lint
        run: npm run lint

      - name: Check Types
        run: npm run typecheck

      - name: Generate Report Unit Test
        run: npm run coverage

      - name: Build Next.js application
        env:
          # These NEXT_PUBLIC_ variables are required for the 'next build' command
          # Ensure these are configured as secrets in your GitHub repository settings
          NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ vars.NEXT_PUBLIC_FIREBASE_PROJECT_ID }} # Or secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID if preferred
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
          NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
        run: npm run build
